name: example_custom_url_shortener
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  app_links: ^6.3.0
  dio: ^5.6.0
  flutter:
    sdk: flutter
  share_plus: ^10.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
